// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql"
)

type Blog struct {
	Bid       int64
	Title     string
	Content   string
	AuthorID  int64
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

type Comment struct {
	Cid       int64
	Content   string
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
	AuthorID  int64
	BlogID    int64
}

type Image struct {
	Iid    int64
	Name   string
	Type   string
	Data   []byte
	UserID sql.NullInt64
}

type RefreshToken struct {
	Tid       int64
	Token     string
	OwnerID   int64
	CreatedAt sql.NullTime
}

type User struct {
	Uid       int64
	Username  string
	Email     string
	Password  sql.NullString
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}
