// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"context"
	"database/sql"
)

type Querier interface {
	AllTokens(ctx context.Context) ([]RefreshToken, error)
	AllUsers(ctx context.Context) ([]User, error)
	CountAllBlogs(ctx context.Context) (int64, error)
	CountAllComments(ctx context.Context) (int64, error)
	CountMyBlogs(ctx context.Context, authorID int64) (int64, error)
	CountMyComments(ctx context.Context, authorID int64) (int64, error)
	CreateToken(ctx context.Context, arg CreateTokenParams) error
	DeleteBlog(ctx context.Context, arg DeleteBlogParams) error
	DeleteComment(ctx context.Context, arg DeleteCommentParams) error
	DeleteCommentByAId(ctx context.Context, arg DeleteCommentByAIdParams) error
	DeleteUser(ctx context.Context, uid int64) error
	GetAllBlogs(ctx context.Context) ([]Blog, error)
	GetAllComments(ctx context.Context) ([]Comment, error)
	GetAuthorName(ctx context.Context, uid int64) (string, error)
	GetBlogByBId(ctx context.Context, bid int64) (Blog, error)
	GetBlogByTitle(ctx context.Context, title string) (Blog, error)
	GetCommentsForBlogByBId(ctx context.Context, bid int64) ([]GetCommentsForBlogByBIdRow, error)
	GetCommentsForUserByAid(ctx context.Context, uid int64) ([]GetCommentsForUserByAidRow, error)
	GetTokenByUid(ctx context.Context, ownerID int64) (RefreshToken, error)
	GetUserBlogs(ctx context.Context, authorID int64) ([]Blog, error)
	GetUserById(ctx context.Context, uid int64) (User, error)
	GetUserByTid(ctx context.Context, tid int64) (GetUserByTidRow, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	GetUserProfilePic(ctx context.Context, userID sql.NullInt64) (GetUserProfilePicRow, error)
	Login(ctx context.Context, arg LoginParams) (User, error)
	Logout(ctx context.Context, ownerID int64) error
	NewBlog(ctx context.Context, arg NewBlogParams) error
	NewComment(ctx context.Context, arg NewCommentParams) error
	Pagination(ctx context.Context, arg PaginationParams) ([]Blog, error)
	Register(ctx context.Context, arg RegisterParams) error
	UpdateBlog(ctx context.Context, arg UpdateBlogParams) error
	UpdateBlogByBId(ctx context.Context, arg UpdateBlogByBIdParams) error
	UpdateComment(ctx context.Context, arg UpdateCommentParams) error
	UpdateCommentbyAId(ctx context.Context, arg UpdateCommentbyAIdParams) error
	UpdateToken(ctx context.Context, arg UpdateTokenParams) error
	UpdateUser(ctx context.Context, arg UpdateUserParams) error
	UpdateUserPic(ctx context.Context, arg UpdateUserPicParams) error
}

var _ Querier = (*Queries)(nil)
